### ISSUE TITLE
Not Ploting

### ISSUE THREAD

**Issue by kml13** [lhalloran/ERTplot#1]
Actually am newbie to Python and github also.
when i run ERTplot.py code i didnt find any graphs.
then searched on google 

You can write the following at the end of ERTplot code
plt.show()

thats all. Now run. you will see plot. :)

**Comment by lhalloran** [comment]
Hi Kamal, I am not sure which distribution of python you are using. With Anaconda using automatic (not inline) graphics backend  in the ipython console, you don't need plt.show().
